config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('picture_upload.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picture_upload/urls.py
from django.urls import path
from . import views

app_name = 'picture_upload'
urlpatterns = [
    path('', views.UploadImageCreateView.as_view(), name='index'),
    path('result/<int:pk>/', views.UploadImageDetailView.as_view(), name='result'),
]

picture_upload/models.py
from django.db import models
import os
from django.core.exceptions import ValidationError
import io
from PIL import Image
from django.conf import settings


def validate_is_picture(value):
    ext = os.path.splitext(value.name)[1]

    if not ext.lower() in ['.jpg', '.png', '.jpeg']:
        raise ValidationError('Only picure files are availables.')

MAX_SIZE    = 1 * 1000 * 1000

def validate_max_size(value):
    if value.size > MAX_SIZE:
        print('ファイルサイズが上限' + str(MAX_SIZE/1000000) + 'MBを超えています。送信されたファイルサイズ: ' + str(value.size/1000000) + "MB")
        raise ValidationError( "ファイルサイズが上限(" + str(MAX_SIZE/1000000) + "MB)を超えています。送信されたファイルサイズ: " + str(value.size/1000000) + "MB")

    else:
        print("問題なし")


class Styles(models.Model):
    id = models.AutoField(primary_key=True)
    style_image = models.ImageField(verbose_name='style_image',upload_to='styles_img/',)
    style_num = models.IntegerField()

    class Meta:
        verbose_name_plural = 'Styles'


class UploadImage(models.Model):
    id = models.AutoField(primary_key=True)
    contents_image = models.ImageField(verbose_name='contents_image', upload_to='img/', validators=[validate_is_picture, validate_max_size],)
    style_num = models.ForeignKey(Styles, on_delete=models.CASCADE)
    created_image = models.ImageField(verbose_name='created_image', upload_to='created_img/',)

    class Meta:
        verbose_name_plural = 'UploadImage'

    def transform(self):

        # アップロードされたファイルから画像オブジェクト生成
        org_img = Image.open(self.contents_image)

        # PILでの画像処理ここから！
        gray_img = org_img.convert('L')

        # PILでの画像処理ここまで！

        # 画像処理後の画像のデータをbufferに保存
        buffer = io.BytesIO()
        gray_img.save(fp=buffer, format=org_img.format)

        # 以前保存した画像処理後の画像ファイルを削除
        self.created_image.delete()

        # bufferのデータをファイルとして保存（レコードの更新も行われる）
        self.created_image.save(name=self.contents_image.name, content=buffer)

picture_upload/forms.py
import os
from django import forms
from .models import UploadImage

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UploadImage
        fields = ('contents_image', 'style_num',)

picture_upload/views.py
#import tensorflow as tf

from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from .models import UploadImage, Styles
from django.views import generic
from .forms import UploadImageForm
import cv2
from config import settings_dev

#ai_model = tf.keras.models.load_model('../my_model.h5')

def gray(input_url,output_url):
    img = cv2.imread(input_url)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    cv2.imwrite(output_url, img_gray)

class UploadImageCreateView(generic.CreateView):
    model = UploadImage
    template_name = 'index.html'
    form_class = UploadImageForm
    extra_context = {
        "list": Styles.objects.all(),
    }
    
    #formでPOSTされたときにform_validメソッドが呼び出される
    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.transform()
        return response


    #def form_valid(self, form):
        #アップされたインスタンスを持ってくる
        #data = form.cleaned_data
        #print(data)
        #obj = UploadImage(**data)
        #obj.save
        #print(obj.contents_image.url)
        #print(obj.pk)
        ##白黒変換
        #input_url = str(settings_dev.BASE_DIR) + obj.contents_image.url
        #output_url = str(settings_dev.BASE_DIR) + "/media/created_img/" + str(obj.pk) + ".jpg"
        #print(input_url)
        #print(output_url)
        #gray(input_url, output_url)
        ##データベースに加工した画像を登録
        #obj.created_image = "/created_img/" + str(obj.pk) + ".jpg"
        #obj.save()
        #return super().form_valid(form)

    def get_success_url(self):
        return reverse('picture_upload:result', kwargs={'pk':self.object.pk})



class UploadImageDetailView(generic.DetailView):
    model = UploadImage
    template_name = 'result.html'

picture_upload/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Grayscale Transform</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/index.css' %}" rel="stylesheet">
        <!-- slick css-->
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
        <!-- JavaScript-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Grayscale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <section>
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-6">
                        <h1 class="mt-5">Grayscale</h1>
                        <p>Convert an image to grayscale.</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Form -->
        <section>
         <div class="container px-4 px-lg-5">
           <div class="row gx-4 gx-lg-5">
             <div class="col-lg-6 mx-auto">
               <form method="post" enctype="multipart/form-data" action="/" class="mx-auto">
                {% csrf_token %}
                <label class="preview my-5 mx-auto" id="preview">
                  <img class="img--preview" src="{{ img_path }}">
                  <input name="contents_image" type="file" accept="image/*" required="">
                </label>
                
                <div class="single-item">
                <label for="id_style_num">
                  <img class="select" src="{{list.0.style_image.url}}">
                  <input type="radio" name="style_num" required id="id_style_num0" value="{{list.0.style_num}}">
                </label>
                <label for="id_style_num1">
                  <img class="select" src="{{list.1.style_image.url}}">
                  <input type="radio" name="style_num" required id="id_style_num1" value="{{list.1.style_num}}">
                </label>
                </div>

                <label for="submit" class="submit my-5 mx-auto">
                  <input id="submit" name="file" type="submit" accept="image/*" required="">
                  <p>submit</p>
                </label>
               </form>
              </div>
             </div>
           </div>
         </section>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- slick -->>
        <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
　　　　 <script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

      　<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slick.js' %}"></script>
    </body>
</html>

picture_upload/templates/list_result.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>test</title>
</head>
<body>
    <div>
        {% for object in object_list %}
        <h2>ID:{{object.style_num.style_num}}の画像</h2>
        {% if object.contents_image %}
            <img src="{{object.contents_image.url}}">
        {% endif %}
        <h2>ID:{{object.style_num.style_num}}の画像</h2>
        <img class="img--preview" src="{{object.style_num.style_image.url}}">
        {% endfor %}
    </div>
</body>
</html>

picture_upload/templates/result copy.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>test</title>
</head>
<body>
    <div>
        <div class="col-3">
            {% if object.contents_image %}
            <img src="{{ object.contents_image.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.contents_image %}
            <img src="{{ object.style_num.style_image.url }}" width="200" height="200"/>
            {% endif %}
        </div>
    </div>
</body>
</html>

picture_upload/templates/result.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Grayscale Transform</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/index.css' %}" rel="stylesheet">
        <!-- slick css-->
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
        <!-- JavaScript-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Grayscale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <section>
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-6">
                        <h1 class="mt-5">Grayscale</h1>
                        <p>Convert an image to grayscale.</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Form -->
        <div class="col-3">
            {% if object.contents_image %}
            <img src="{{ object.contents_image.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.created_image %}
            <img src="{{ object.created_image.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.contents_image %}
            <img src="{{ object.style_num.style_image.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- slick -->>
        <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
　　　　 <script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

      　<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slick.js' %}"></script>
    </body>
</html>